>>> lat_dim value: 60
>>> mode is: jonatank
(780, 666)
CAME HERE!! 1
CAME HERE!! 11
2020-09-30 19:30:37.916169: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-30 19:30:38.159634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:04:00.0
totalMemory: 10.73GiB freeMemory: 10.57GiB
2020-09-30 19:30:38.159693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:30:44.321471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:30:44.322087: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:30:44.322104: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:30:44.322411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10203 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
2020-09-30 19:30:44.324168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-09-30 19:30:44.324256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-30 19:30:44.324276: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-09-30 19:30:44.324289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-09-30 19:30:44.324630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/device:GPU:0 with 10203 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:04:00.0, compute capability: 7.5)
True
CAME HERE!! 12
CAME HERE!! 2
CAME HERE!! 3
CAME HERE!! 31
CAME HERE!! 32
Initialized parameters
CAME HERE!! 33
CAME HERE!! 4
Traceback (most recent call last):
  File "train_vae.py", line 301, in <module>
    test_batch = MRi.get_patch(batch_size, test=True)
  File "/scratch_net/bmicdl03/jonatank/code/ddp/dataloader.py", line 137, in get_patch
    patchindexr = np.random.randint(0, fdset['reconstruction_rss'][sliceindex[0]].shape[0] - self.patchsize)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/selections.py", line 94, in select
    sel[args]
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/selections.py", line 261, in __getitem__
    start, count, step, scalar = _handle_simple(self.shape,args)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/selections.py", line 466, in _handle_simple
    x,y,z = _translate_int(int(arg), length)
  File "/scratch_net/bmicdl03/jonatank/conda_envs/tfv1/lib/python2.7/site-packages/h5py/_hl/selections.py", line 486, in _translate_int
    raise ValueError("Index (%s) out of range (0-%s)" % (exp, length-1))
ValueError: Index (227) out of range (0-15)
